spring:
  datasource:
    url: jdbc:mysql://${RDB_HOST}:${RDB_PORT}/${RDB_SCHEMA}?serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: ${RDB_USER}
    password: ${RDB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update